### PR TITLE
Hotfix/emailvalidation

### LINKED ISSUE #19: Validations produce dual errors.
Also validations on email uniqueness doesn't work at all.

When saving user details that is...

### PR DESCRIPTION
**Pull request by Mxiim**
Fixes #19, review

### CODE REVIEW

File: config/routes.rb [hunk 1]
```diff
@@ -35,6 +35,9 @@
   get '/me' => 'users#me', as: :me
   get '/me/edit' => 'users#edit', as: :edit_me
   patch '/me' => 'users#update', as: :update_me
+  get '/users/:id/edit' => 'users#edit_user', as: :edit_user
+  patch '/users/:id/update' => 'users#update_user', as: :update_user
+  get '/users/:id/remove_avatar' => 'users#remove_avatar', as: :remove_avatar
```
Comment (lindskogen) [inline config/routes.rb:41]: why not just `resource :users`?

File: app/views/users/show.html.erb [hunk 2]
```diff
@@ -1,6 +1,9 @@
 <% content_for :title, @user.name_and_nick %>
 <% if @user.admin? %>
-    <% content_for :labels do  %><span class="admin-label">Admin</span><% end %>
+    <% content_for :labels do  %>
+    <span class="admin-label" style="margin-bottom: 2px;">Admin</span>
+    <%= link_to edit_user_path(@user) do %><%= fa_icon 'cog', text: 'Ändra' %><%- end -%>
```
Comment (lindskogen) [inline app/views/users/show.html.erb]: Localize! Localize! Localize!
